version: '3.8'

volumes:
  postgres_data:
  static:
  media:
  nginx_conf:

services:

  db:
    image: postgres:12.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: azeron/yamdb:latest
    command: gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
    restart: always
    env_file:
      - ./.env
    volumes:
      - static:/code/static
      - media:/code/media
      - nginx_conf:/code/conf/
    entrypoint: /code/entrypoint.sh

  nginx:
    image: nginx:latest
    volumes:
      - static:/code/static
      - media:/code/media
      - nginx_conf:/etc/nginx/conf.d/
    ports:
      - "8001:80"
    depends_on:
      - web
    restart: always
